steps:
- name: 'gcr.io/cloud-builders/mvn'
  dir: 'myjavaapp1'              # Run Maven inside myjavaapp folder
  args: ['clean', 'install']

- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/myjavaapp1',
    '-f', 'myjavaapp1/Dockerfile',  # Point to Dockerfile inside myjavaapp
    'myjavaapp'                    # Set build context to myjavaapp folder
  ]

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/myjavaapp1']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy', 'myjavaapp1',
    '--image', 'gcr.io/$PROJECT_ID/myjavaapp1',
    '--platform', 'managed',
    '--region', 'us-central1',
    '--allow-unauthenticated'
  ]

options:
  logging: CLOUD_LOGGING_ONLY
